export const CHANGE_SEARH = "CHANGE_SEARH";
export const SUBMIT_SEARCH = "SUBMIT_SEARCH";
export const ERROR_SEARCH = "ERROR_SEARCH";
export const NEW_SEARCH_DATA = "NEW_SEARCH_DATA";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
export const DROP_CART_ITEM = "DROP_CART_ITEM";

//
